-- 코드를 입력하세요
#SELECT DATE_FORMAT(DATETIME, "%H") as 'HOUR', COUNT(*) FROM ANIMAL_OUTS WHERE DATE_FORMAT(DATETIME, "%H") < 24 GROUP BY HOUR ORDER BY HOUR ASC

SELECT * FROM ANIMAL_OUTS ORDER BY DATE_FORMAT(DATETIME, "%H") ASC
